### ISSUE TITLE
Issues on localhost

### ISSUE THREAD

**Issue by narangrishab** [numtel/mysql-live-select#18]
=> Meteor server restarted                    
W20150904-14:24:09.988(5.5)? (STDERR) 
W20150904-14:24:09.988(5.5)? (STDERR) /Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
W20150904-14:24:09.989(5.5)? (STDERR)         throw err;
W20150904-14:24:09.989(5.5)? (STDERR)               ^
W20150904-14:24:09.989(5.5)? (STDERR) Error: ER_MASTER_FATAL_ERROR_READING_BINLOG: Could not open log file
W20150904-14:24:09.989(5.5)? (STDERR)     at Binlog.Sequence._packetToError (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20150904-14:24:09.989(5.5)? (STDERR)     at Binlog.Sequence.ErrorPacket (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:109:17)
W20150904-14:24:09.989(5.5)? (STDERR)     at Protocol._parsePacket (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20150904-14:24:09.989(5.5)? (STDERR)     at Parser.write (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20150904-14:24:09.990(5.5)? (STDERR)     at Protocol.write (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20150904-14:24:09.990(5.5)? (STDERR)     at Socket.<anonymous> (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20150904-14:24:09.990(5.5)? (STDERR)     at Socket.emit (events.js:95:17)
W20150904-14:24:09.990(5.5)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20150904-14:24:09.990(5.5)? (STDERR)     at Socket.emit (events.js:92:17)
W20150904-14:24:09.990(5.5)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20150904-14:24:09.990(5.5)? (STDERR)     --------------------
W20150904-14:24:09.990(5.5)? (STDERR)     at Protocol._enqueue (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20150904-14:24:09.990(5.5)? (STDERR)     at Object._start [as _onImmediate] (/Users/rishabh/.meteor/packages/numtel_mysql/.1.0.2.lqfdsj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:173:31)
W20150904-14:24:09.990(5.5)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:354:15)
=> Exited with code: 8

**Comment by numtel** [comment]
Is this really an issue? Looks like a configuration problem.
