### ISSUE TITLE
No reactivity with views

### ISSUE THREAD

**Issue by nitinkumarmedia** [numtel/mysql-live-select#23]
Hi,

I have created view in mysql database. When I change something in tables, it updates the view but reactivity with view is not working. I can't see new data populated in UI when view updates. Reactivity works with tables perfectly if I connect UI with tables but not with views. 

Is there any way to set it up?

Regards,
Nitin

**Comment by numtel** [comment]
Can you post your code? You will still need to define triggers based on the tables that the view depends upon.

**Comment by nitinkumarmedia** [comment]
Aah, thank you Ben! It works now. 

I have added the triggers like this for all the database tables used in the view script:

return mysqlDB.select(
  'select * from VIEW,
  [ {table: 'TABLE1', database: 'DB1'}, {table: 'TABLE2', database: 'DB2'}, {table: 'TABLE3', database: 'DB3'}]
);

This might be helpful for others in future.
