### ISSUE TITLE
[question] If self.emit.apply(self, arguments) return false, what does it mean?

### ISSUE THREAD

**Issue by wuxianliang** [numtel/mysql-live-select#3]
Dear @numtel 
I am debugging my meteorient project which is modifying mysql-live-select. I invert two console.logs in codes.

```javascript
var abc = self.emit('update', records);
  console.log(abc);
```

```javascript
var diffEvent = function(){
      var abc = self.emit.apply(self, arguments);
      console.log(abc);
      diff.push(Array.prototype.slice.call(arguments));
    }

```

the first one returns true, so I think emitter works. When the second one was called, it returns false every time. So I think that is why I can't find data on client side-- event emited false.

How to check reasons further? I am going to check subscription.

Thank you very much.

**Comment by numtel** [comment]
Please do not ask general Node.js questions in my issues.

Look at [the documentation for `EventEmitter`](http://nodejs.org/api/events.html#events_emitter_emit_event_arg1_arg2) to see why this behavior is occuring.

**Comment by wuxianliang** [comment]
Thank you for the link. I will not ask such general questions again. I just did not realize that how far this project will lead me to. Now no matter how far it is, I will be there.
