### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by trusktr** [numtel/mysql-live-select#6]
Is the MYSQL db being polled at some interval? Or does MYSQL have it's own event system that you are listening to?

**Comment by peterchoo** [comment]
It uses the MySQL binary log (used for replication and data recovery) to see what has changed in the database and update the search queries you've requested.

**Comment by trusktr** [comment]
@peterchoo Awesome. So is the app periodically reading the log in some timed interval? Or is there some type of communication mechanism that allows apps to subscribe to mysql's changes and the changes are pushed to the apps?

**Comment by peterchoo** [comment]
It's set up as a replication client, so the binary log is pushed from the
mysql db in real time. Have a look at mysql bin log replication.  The live
select module monitors the log for changes to the data in the queries
you've registered with it and pushes the changes.

**Comment by trusktr** [comment]
Thanks a ton @peterchoo (:
