### ISSUE TITLE
using live select on large tables

### ISSUE THREAD

**Issue by behrad** [numtel/mysql-live-select#7]
We have a table with a 50 million rows, and 50 inserts/sec in production, Can I use mysql-live-select to only receive inserted items (`select ... where id > lastSavePointId`) without polling on such a big table? 

Won't enabling binlog hurt my production environment on such a big db? any side effects? impact on server? I'm unfamiliar with it :)

Very excited when see this :+1:

**Comment by numtel** [comment]
Going to close this. Speculation is not an issue. If you try it and you have problems please report back. @vlasky seems to be having good luck with large loads. Especially with versions >=0.0.24.
