### ISSUE TITLE
'added' event does not necessarily provide actually added row

### ISSUE THREAD

**Issue by tandrew** [numtel/mysql-live-select#9]
When using the [numtel:meteor-mysql] (https://github.com/numtel/meteor-mysql) package within a Meteor project I encountered an interesting phenomenon:
When using an even listener on the "added" event, the index and row returned are not necessarily the actually added row, which is what I expected.

It rather seems it is the last row of the result set which is returned by the MySQL statement executed. 

So let's say you have a statement "SELECT * from MYSQL_TABLE" which returns rows in an arbitrary order as determined by the MySQL engine due to the lack of an "order by" clause.

ID | NAME
------------ | -------------
10 | JACK
20 | JOHN
30 | SAM

Next you insert a new row into the MySql DB using MySql Workbench which looks like this:

ID | NAME
------------ | -------------
15 | CHUCK

The "SELECT * FROM MYSQL_TABLE" statement now returns:

ID | NAME
------------ | -------------
10 | JACK
15 | CHUCK
20 | JOHN
30 | SAM

In this order. Yeah, not 

ID | NAME
------------ | -------------
10 | JACK
20 | JOHN
30 | SAM
15 | CHUCK

I was under the impression that the 'added' listener would return the value of the new row 15/CHUCK.
But instead it returns 

ID | NAME
------------ | -------------
30 | SAM

Which also turns out to be the last row returned by SELECT * FROM MYSQL_TABLE statement when you fire it in the MySql Workbench (see above).

**Question:**
How can we ensure that the row returned by the 'added' event is actually the added row?

One easy workaround is to modify the table and statement like this:
"SELECT * FROM MYSQL_TABLE ORDER BY MODIFIED_DATE" where the new column "MODIFIED_DATE" defaults to NOW().
This ensures that the last row returned by the statement is always the newest one. But I believe this is not the intended behavior and it is likely that I am making a stupid mistake somewhere ...

I am a newbie to all of this so I may just overlook something very simple, in which case I would appreciate anyone helping me out on this.

Please see examples of the code below.

Server file "mysql_table.js"

```javascript
Meteor.publish('mysql_table', function (limit) {
    return liveDb.select(
        'SELECT * FROM mysql_table ''),
        [{
            table: 'mysql_table'
        }]
    )
})
;
```

Server file "methods.js"

```javascript
Meteor.methods ({
   'mysql_table.upsert': function (index, row) {
        my_mongo_collection.update(
            { myid: row.ID },
            {
               myid: row.ID,
                name: row.NAME
             },
            {upsert: true}
        );
})
```

Common file "myCollection.js"

```javascript
my_mongo_collection = new Mongo.Collection("my_mongo_collection");

mysql_table = new MysqlSubscription('mysql_table');

mysql_table.addEventListener('error', function (error) {
    console.log('mysql_table -> error: ', error);
});

// 'added' event listener
mysql_table.addEventListener('added', function (index, row) {
    // -> index and row passed here are most likely not the actually added row 
    // if they are, then it's a coincidence!
    console.log('mysql_table -> added -> index: ', index);
    console.log('mysql_table -> added -> row: ', row); 
    Meteor.call('mysql_table.upsert', index, row); // calling upsert server side
});
```

Any enlightenment on this much appreciated.

- Andrew

**Comment by numtel** [comment]
With versions >1.0 the diffing calculation has been changed and these events have been removed. All updates now come in the `update` event.
